### ISSUE TITLE
"Add Use a DONE marker when recordings on the Archives page" not working for me

### ISSUE THREAD

**Issue by jwhonce** [YU000jp/logseq-plugin-quickly-para-method#24]
`Recode > Add a DONE marker when recording on the Archives` is checked
plugin v1.8.5
Logseq Version 0.10.7 (81)
macOS 14.4 (23E214)

Reading https://github.com/YU000jp/logseq-plugin-quickly-para-method/pull/5 , it would appear archiving a project using `/Page-Tag (Archive)` should update `[[Archives]]` with DONE and a reference to the archived project. This does not happen on my instance of Logseq.  The project page's tags are changed from `Projects` to `Archives`, but neither the `[[Projects]]` or `[[Archives]]` pages are updated as I would expect.

* Invoking tagging to `Archives` using the menu has the same behavior. 
* I see no errors in the console using the developer tools.
* Restarting Logseq did not change the behavior.
* Refreshing the graph did not change the behavior.

Is there any additional information I can provide to debug the issue?

**Comment by YU000jp** [comment]
The cause is currently unknown. It's working in my environment. This option itself does not require a complicated amount of code, so the cause is likely to be limited, but I do not know. I'll put this issue on hold. https://github.com/YU000jp/logseq-plugin-quickly-para-method/blob/6fb4e6f43814923d0161d3fcc8d8412cc41ddd7e/src/RecodePageTop.ts#L25

**Comment by YU000jp** [comment]
Note that there is the toggle in the plugin settings, please enable it.

**Comment by YU000jp** [comment]
This option does not mean placing the DONE marker on the page itself, but rather on the block used to record the date.
